-- Autogenerated from types.go by sqlgen; DO NOT EDIT.

CREATE TABLE schema_version (
  Name TEXT PRIMARY KEY,
  Version INTEGER NOT NULL
) STRICT;
INSERT INTO schema_version (Name, Version) VALUES ('main', 1);

CREATE TABLE safe_ids (
  ID INTEGER PRIMARY KEY,
  Type TEXT NOT NULL
) STRICT;

CREATE TABLE users (
  ID INTEGER PRIMARY KEY,
  JSONObj BLOB NOT NULL,
  CreatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.CreatedAt')) STORED,
  UpdatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.UpdatedAt')) STORED,
  stored TEXT NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.Email') STORED
) STRICT;
CREATE UNIQUE INDEX users_stored ON users (stored);

CREATE TABLE user_projects (
  ID INTEGER PRIMARY KEY,
  JSONObj BLOB NOT NULL,
  CreatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.CreatedAt')) STORED,
  UpdatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.UpdatedAt')) STORED,
  UserID INTEGER NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.UserID') STORED,
  ProjectID INTEGER NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.ProjectID') STORED
) STRICT;
CREATE UNIQUE INDEX user_project_unique ON user_projects (UserID, ProjectID);
