-- Autogenerated from types.go by sqlgen; DO NOT EDIT.

CREATE TABLE schema_version (
  Name TEXT PRIMARY KEY,
  Version INTEGER NOT NULL
) STRICT;
INSERT INTO schema_version (Name, Version) VALUES ('main', 1);

CREATE TABLE safe_ids (
  ID INTEGER PRIMARY KEY,
  Type TEXT NOT NULL
) STRICT;

CREATE TABLE users (
  ID INTEGER PRIMARY KEY,
  JSONObj BLOB NOT NULL,
  CreatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.CreatedAt')) STORED,
  UpdatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.UpdatedAt')) STORED,
  Email TEXT NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.Email') STORED
) STRICT;
CREATE UNIQUE INDEX users_email ON users (Email);

CREATE TABLE user_projects (
  ID INTEGER PRIMARY KEY,
  JSONObj BLOB NOT NULL,
  CreatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.CreatedAt')) STORED,
  UpdatedAt INTEGER NOT NULL GENERATED ALWAYS AS (strftime('%s', JSONObj->>'$.UpdatedAt')) STORED,
  UserID INTEGER NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.UserID') STORED,
  ProjectID INTEGER NOT NULL GENERATED ALWAYS AS (JSONObj->>'$.ProjectID') STORED,
  FOREIGN KEY (UserID) REFERENCES users(ID) ON DELETE CASCADE
) STRICT;
CREATE INDEX user_projects_user_id ON user_projects (UserID);
CREATE INDEX user_projects_project_id ON user_projects (ProjectID);
CREATE UNIQUE INDEX user_project_unique ON user_projects (UserID, ProjectID);
